### PR TITLE
Include CSS in bower.json main

### PR DESCRIPTION
**Pull request by frapontillo**
The Bower JSON needs to include CSS files as well, beyond scripts. See [spec](https://github.com/bower/bower.json-spec#main).

### CODE REVIEW

**Comment by istvan-ujjmeszaros** [comment]
Thanks @frapontillo, I made a new release.

**Comment by frapontillo** [comment]
Thank you for the quickness! :ship:

**Comment by istvan-ujjmeszaros** [comment]
Np, I don't have too much time nowadays so I have added you as a collaborator if you don't mind.

**Comment by frapontillo** [comment]
Sure, no problem! I'd still go through the PR way so you can approve at least the general ideas behind changes.

**Pull request merged**
